# Generated by Django 5.2 on 2025-12-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
