# Generated by Django 5.2 on 2025-12-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_transaction_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransaction',
            name='kind',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('GASTO', 'Gasto'), ('TRANSFERENCIA', 'Transferencia'), ('PAGO_TARJETA', 'Pago de Tarjeta'), ('TRANSFERENCIA_EXTERNA', 'Transf. Externa')], max_length=25),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='kind',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('GASTO', 'Gasto'), ('TRANSFERENCIA', 'Transferencia'), ('PAGO_TARJETA', 'Pago de Tarjeta'), ('TRANSFERENCIA_EXTERNA', 'Transf. Externa')], max_length=25),
        ),
    ]
